### ISSUE TITLE
Update project description to include more NETL project info

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#105]
This description still reflect the so-called 'phase I' but doesn't capture the phase II netl work

**Comment by WesIngwersen** [comment]
Actually I see that the [NETL contract with ERG is mentioned ](https://github.com/USEPA/ElectricityLCI/blob/037fa4e4658ce0007f1d80ad7de35072ebe3eb78/electricitylci/data/process_metadata.yml#L114) but wondering if any more description is needed

**Comment by jump2conclusionsmatt** [comment]
[Latest metadata commit](https://github.com/USEPA/ElectricityLCI/commit/bbdd7a2c4fca8b0c45991f9e3e3607bff735fcb2) should handle this.
