### ISSUE TITLE
Need at least one documentation source

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#107]
We need  to add at least one documentation source so that users can find documentation

**Comment by WesIngwersen** [comment]
The upstream datasets should also have a documentation source that is perhaps separate if available

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt I started a metadata_fixes branch for working on these different issues with the metadata tag

**Comment by bl-young** [comment]
Flagging this so we can make sure the upstream models use the same source. @dannyhage

We have sources for both coal and gas - but it might make sense to generate them (and their UUIDs) with the code instead.

**Comment by jump2conclusionsmatt** [comment]
Someone please correct me if I'm wrong, but there doesn't appear to be any examples for entering openLCA "sources" correct? The request is to add these? This might take some work  - will need to structure the data correctly within process_metadata.yml and then correctly implement it within process_dictionary_writer.py.

If openLCA "sources" aren't needed, I tried to provide links to data sources within the metadata text.

**Comment by bl-young** [comment]
I'm not familiar with a way to access sources within a process for the ipc. But it does look like you can create a source and add it to a json.

**Comment by bl-young** [comment]
Sorry looks like I was wrong: http://greendelta.github.io/olca-schema/html/ProcessDocumentation.html

**Comment by jump2conclusionsmatt** [comment]
I think it'll be alright. [olca_jsonld_writer](https://github.com/USEPA/ElectricityLCI/blob/a1ad6f3763075a55d47281a4b7a53b540732bb17/electricitylci/olca_jsonld_writer.py#L316) has a way to generate sources already. I just need to find a clean way to add the sources in the yaml, so that they can be created in jsonld.

**Comment by jump2conclusionsmatt** [comment]
Alright - this has been started. See [process_metadata.yml](https://github.com/USEPA/ElectricityLCI/blob/24dd7b67b82f5da51f1046c401d251d0bd15c3cb/electricitylci/data/process_metadata.yml#L689) for an example source. Anyone have real strong feelings about this format? Seems fairly straightforward. There are some changes in [process_dictionary_writer](https://github.com/USEPA/ElectricityLCI/blob/metadata_fixes/electricitylci/process_dictionary_writer.py) and [olca_json_ld_writer](https://github.com/USEPA/ElectricityLCI/blob/24dd7b67b82f5da51f1046c401d251d0bd15c3cb/electricitylci/olca_jsonld_writer.py#L317) as well. Hopefully the changes to _source don't break anything. It appears to not ever be used, more specifically, no processes every have "publication" defined.

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt Looks great in process_metadata.yml.  Ideally the publication field would only be used when it has the primary documentation to describe that particular process. It's probably more valuable than the Sources field which doesn't necessary suggest exactly how those Sources are used.

**Comment by jump2conclusionsmatt** [comment]
I added the rest of the sources. I was able to run ELCI without failures, so it seems okay. The one thing @WesIngwersen that I wanted to point out was the inclusion of the draft eLCI manuscript as a source. I know we had always intended to include documentation in the manuscript about some of these technologies that aren't well documented already (e.g., solar PV, wind). I don't know how you feel about that: ([link to example](https://github.com/USEPA/ElectricityLCI/blob/8f0014ba3398c9de7c90b55ac6ff6061ec77338e/electricitylci/data/process_metadata.yml#L429))

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt Yes this is fine - we need to make sure we have documentation of the work somewhere and that was one intended source of it. I was hoping to get some more support to finish that..it is well on its way and hope we can find a way to complete it

**Comment by jump2conclusionsmatt** [comment]
Was this kept open because there aren't sources for the technologies or various mixes? I added the eLCI manuscript as the default source to cover this. The one exception that I thought there might be is the eGRID-based consumption mix. @bl-young - didn't Troy have a manuscript for this? Can you post that info here or add it to process_metadata.yaml?

**Comment by hottleta** [comment]
I don't know what the preferred documentation would be but there are several publications in the works, I have been working with @TJTapajyoti to get the trading methodology submitted.

**Comment by jump2conclusionsmatt** [comment]
Similar [to this](https://github.com/USEPA/ElectricityLCI/blob/8f0014ba3398c9de7c90b55ac6ff6061ec77338e/electricitylci/data/process_metadata.yml#L429), I would just mark it as in preparation and put today's years and an author list. Just to give people the idea that documentation is in works somewhere. If it changes down the line, we can just update the metadata. So I just need a working title and authors I guess.

**Comment by WesIngwersen** [comment]
@hottleta @jump2conclusionsmatt  Closing this issue for now as Matt put a temp reference in for the Hottle trade methodology in this [commit](https://github.com/USEPA/ElectricityLCI/commit/f6d07f557ff1dba28d947c9057965dce7dabd675)
