### ISSUE TITLE
Need to specifiy model # and electricitylci version # in metadata

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#108]
For full transparency, somewhere in the metadata we need to specify the selected model and the electricitylci version number in the process metadata. Ideally these would be automatically added and not manually added. Of course there needs to be a link to this github

**Comment by WesIngwersen** [comment]
Reopening because this is not appearing in the process metadata

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt Although I added this in the two commits above, I think it's not getting written into the final metadata.

**Comment by jump2conclusionsmatt** [comment]
For me, the version information was working correctly for generators, generation mixes, and consumption mixes. I added commit [cf76740](https://github.com/USEPA/ElectricityLCI/commit/cf76740e3fdcd6a702d8d64209ed1150b8263edd) to add it to upstream processes (e.g., coal extraction and processing) as well.

**Comment by jump2conclusionsmatt** [comment]
More commits added to address this for everthing. 
ed4140a83686d7e5274c2892d08b43c7a60a552b
abbd5a85c5c98473cbee735277a0f8d3a5f25ef3
49c13e6b0a05fd442340e105a216295d4bef14de
