### ISSUE TITLE
Co2 input emissions in diesel process

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#113]
Note: I have not checked yet, but this could be an issue in the other RFO processes as well.

openLCA is not handling well the diesel upstream processes (e.g. petroleum extraction and processing – DFO PADD 1) which have CO2 emissions as both an input and an output. In LCIA these emissions are not being characterized correctly.

**Comment by jump2conclusionsmatt** [comment]
Open branch [issues/113](http://github.com/USEPA/ElectricityLCI/tree/issues/113) to address this comment. The carbon dioxide emissions listed as inputs in the excel inventory data spreadsheets (e.g., [PRELIM_Mixer__Diesel___PADD_1_.xlsx](https://github.com/USEPA/ElectricityLCI/blob/master/electricitylci/data/petroleum_inventory/PRELIM_Mixer__Diesel___PADD_1_.xlsx)) were changed to outputs. These were intended to represent the emissions from land use change that are accounted for in OPGEE.
