### ISSUE TITLE
Missing generation processes, eLCI1 (v1.0)

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#116]
The following generation processes are missing, despite being referenced by generation mixes:

OFSL - Midcontinent   Independent System Operator, Inc.
OIL - El Paso Electric Company
OTHF - Nevada Power Company

Quantities consumed tend to be quite small <1% of generation mix.

Related to https://github.com/USEPA/ElectricityLCI/issues/77

**Comment by jump2conclusionsmatt** [comment]
All these processes are being created now - fixed in pull request #130.
