### ISSUE TITLE
Error linking consumption mixes, eLCI1 (v1.0)

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#117]
Several consumption mixes have a near-zero input from the generation mix (1E-15)

Electricity; at   grid; consumption mix - Alcoa Power Generating, Inc. - Yadkin Division
Electricity; at grid; consumption mix -   Gridforce South
Electricity; at grid; consumption mix -   Griffith Energy, LLC
Electricity; at grid; consumption mix -   NaturEner Power Watch, LLC (GWA)
Electricity; at grid; consumption mix -   NaturEner Wind Watch, LLC
Electricity; at grid; consumption mix -   New Harquahala Generating Company, LLC - HGBA
Electricity; at grid; consumption mix -   Southeastern Power Administration
Electricity; at grid; consumption mix -   Western Area Power Administration - Upper Great Plains East

In most cases the generation processes exist and therefore are not being pulled accurately.

**Comment by bl-young** [comment]
Note some overlap with #119

**Comment by jump2conclusionsmatt** [comment]
These are intentional - they are balancing authority areas that are net exporters. I just set a very small input so that the consumption mix plans would generate _something_. Prior to setting to 1E-15, the consumption mix processes weren't getting generated.

**Comment by WesIngwersen** [comment]
@bl-young suggests to remove these small fractions out and renormalize the totals to add to 1 with the remaining fractions

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt  suggests we could manually find an energy mix for these BAs missing generation mixes

**Comment by bl-young** [comment]
@WesIngwersen I think your comments are swapped. The comments here apply to #119 and the comments there apply here (though there is some overlap)

**Comment by jump2conclusionsmatt** [comment]
Started branch [issues/117_119](https://github.com/USEPA/ElectricityLCI/tree/issues/117_119) for this. As discussed, the BAs that are purely exporting BAs are not having consumption mixes generated. The current changes in the branch achieve this. There are still consumption mixes at user that are still being generated. Will probably end up just dropping those from the dictionary at the time of posting the warnings about them.

**Comment by jump2conclusionsmatt** [comment]
Fixed with pull request #135.
