### ISSUE TITLE
Special character issue in generation processes, eLCI1 (v1.0)

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#118]
Data Treatment field contains strange characters in some of the descriptions

![image](https://user-images.githubusercontent.com/44471635/87715632-a4eb2480-c77b-11ea-9ee4-142b52c1c8de.png)

**Comment by jump2conclusionsmatt** [comment]
Removed special characters in process_metadata.yml. Already pulled in.
