### ISSUE TITLE
consumption mixes for Canada, eLCI1 (v1.0)

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#120]
The following exist but are unconnected and should probably be removed. New Brunswick could be connected to the underlying generation mix as an alternative.

Electricity; at user; consumption mix - Canada
Electricity; at user; consumption mix -   New Brunswick System Operator

**Comment by WesIngwersen** [comment]
could omit consumption mixes that are not within the US

**Comment by jump2conclusionsmatt** [comment]
This should be fixed in the issues/120 branch. We're just not creating at user consumption mixes for anything missing at that point.
