### ISSUE TITLE
High PM emissions at Duke Energy Progress East

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#121]
associated with solar generation

**Comment by jump2conclusionsmatt** [comment]
This may go away with proposed fix to #77 - re-categorizing plants based on EIA923 fuel consumption.

**Comment by jump2conclusionsmatt** [comment]
Note that this also applies to SOLAR - California Independent System Operator.

**Comment by jump2conclusionsmatt** [comment]
Finally remembered where I documented some of this. It ties back to [stewi issue 25](https://github.com/USEPA/standardizedinventories/issues/25). For the plants listed in that issue (55077 - the NGCC plant and 56944 - the PV plant), 55077 only ends up with emissions from amp_plant_emissions (CO2, CH4, NOx, N2O, and SO2), while 56944 has all the NEI, RCRA, and TRI emissions (which all should probably be 0) along with the emissions from the NETL PV construction LCI.
Note that these are the plants for the Cal ISO problem.

I'll have to look into the Duke Energy Progress, but I suspect it's something similar. 

For the CAL ISO problem, I think the easiest fix is to just re-assign all 56944 emissions to 55077 (I guess within generation.py?).

**Comment by jump2conclusionsmatt** [comment]
For Duke Energy Progress East, the offending plant is 56938.
Its [FRS ID](https://ofmpub.epa.gov/frs_public2/fii_query_detail.disp_program_facility?p_registry_id=110000350174) is also associated with a steam plant (2713 - burning mostly DFO) and a combined cycle plant (58697 - burning mostly natural gas). I would suggest re-assigning here as well. 

There may still be an issue of under-reported emissions for 58697 after implementing a fix. There are no emissions from other sources making it into the combined dataframe right now, so unclear if CO2 emissions from amp_plant_emissions will make through after NEI data is re-assigned to it.

**Comment by jump2conclusionsmatt** [comment]
Commits in [issues/121](https://github.com/USEPA/ElectricityLCI/tree/issues/121) takes care of this. As part of this, I implemented away to introduce manual edits using a yaml file. That implementation is probably deserving of its own issue to track improvements and to discuss.

**Comment by jump2conclusionsmatt** [comment]
These issues are fixed with manual edits.

**Comment by dt-woods** [comment]
@m-jamieson, for entries 5, 6, and 7 in manual_edits.yml, the filter column points to "FacilityID" which is heavily replaced with "eGRID_ID" in `create_generation_process_df` in generation.py. 
I'm getting the errors mentioned above with missing providers. Should I change the columns for these entries to match the data frame or is this some side case that I'm just not aware of?
