### ISSUE TITLE
Electricity Sum varies in the same NERC region - Aggregated to NERC regions. 

### ISSUE THREAD

**Issue by TJTapajyoti** [USEPA/ElectricityLCI#155]
This is the version where we are aggregating the inventory to the NERC region. As you can see from the picture,
ASCC. COAL has different electricity sum values. And even the mean column seems different. @jump2conclusionsmatt 

![image](https://user-images.githubusercontent.com/24482959/104411067-f7d54700-5526-11eb-97b5-1b9ed635cd6e.png)

**Comment by jump2conclusionsmatt** [comment]
This is intentional. Flows with different data sources will result in different amounts of electricity. The electricity is the sum of all plants in the region that report to that data source or in other words all plants that report at least 1 NEI emission. In this case, NEI vs egrid.

**Comment by TJTapajyoti** [comment]
@jump2conclusionsmatt  Thanks for the explanation. One question, If I want to derive the total electricity production of a region for a particular fuel source, can I use this column? Or is that information difficult to derive from this document? ( This is the generation_process_df )

**Comment by jump2conclusionsmatt** [comment]
If I were to stick with just that dataframe, taking a max value of that column would be closest. An accurate answer would involve processing the _gen\_plus\_fuels_ dataframe [from here](https://github.com/USEPA/ElectricityLCI/blob/2232c41f2cb4fd333ad59c8710aa55906e6a7ed3/electricitylci/__init__.py#L89) and doing a groupby or something.

**Comment by TJTapajyoti** [comment]
@jump2conclusionsmatt  Thanks. I will close this issue now.
