### ISSUE TITLE
Bulk data format changed

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/ElectricityLCI#169]
In the IO based consumption module [(eia_io_trading.py)](https://github.com/USEPA/ElectricityLCI/blob/master/electricitylci/eia_io_trading.py), there is a data download from the EIA to capture all of the trading data in one file. At some point between v1.0.1 and now, EIA has changed the date/time format in that file, resulting in a runtime error from [line 149](https://github.com/USEPA/ElectricityLCI/blob/2232c41f2cb4fd333ad59c8710aa55906e6a7ed3/electricitylci/eia_io_trading.py#L149).
ValueError: time data '2016-01-01 00:00:00+00:00' does not match format '%Y-%m-%d %H:%M:%S%z'

**Comment by jump2conclusionsmatt** [comment]
So it appears that this used to be an issue with strptime not supporting the ":" in the timezone adjustment "+00:00". Apparently there was a fix in python 3.7 for this, so it's gone away. I'm leaning towards closing this with the expectation that updates to the requirements and setup files will ensure that this won't happen in the future.

**Comment by bl-young** [comment]
I believe 3.6 is about to lose all support so might be good to update the python requirements across the board anyway
