### ISSUE TITLE
Typo in conversion of water volume to mass

### ISSUE THREAD

**Issue by jgrooviest** [USEPA/ElectricityLCI#172]
https://github.com/USEPA/ElectricityLCI/blob/2232c41f2cb4fd333ad59c8710aa55906e6a7ed3/electricitylci/hydro_upstream.py#L59

**Comment by jgrooviest** [comment]
Could be fixing a typo in the original data.

**Comment by jump2conclusionsmatt** [comment]
Duplicate of #153
