### ISSUE TITLE
FileNotFound Error on L53 of nuclear_upstream.py

### ISSUE THREAD

**Issue by dt-woods** [USEPA/ElectricityLCI#176]
**Bug**

The file "data/nuclear_LCI.csv" is not found after installing electricitylci v1.0.1; however, the file "data/nuclear_lci.csv" is there. This appears to be an issue of case sensitivity being ignored on PCs but significant elsewhere. Quick-solved by changing the file name to match the line in the code; a better solution is to fix the code if lower-case filenames are to be used. Examining other file names in the data folder, it doesn't seem to be the case. I guess this is just an FYI for those running this on Mac/Linux.

**Comment by jump2conclusionsmatt** [comment]
Thank you!
