### ISSUE TITLE
Is this working?

### ISSUE THREAD

**Issue by TJTapajyoti** [USEPA/ElectricityLCI#34]
@WesIngwersen  is this line wokring on your end?

Mine says its missing the last column.

                    database_f2 = database_f2[['Subregion', 'FuelCategory', 'PrimaryFuel',
                                               'eGRID_ID', 'Electricity', 'FlowName', 'FlowAmount', 'FlowUUID',
                                               'Compartment', 'Year', 'Source', 'ReliabilityScore', 'Unit',
                                               'NERC', 'PercentGenerationfromDesignatedFuelCategory',
                                               'Balancing Authority Name', 'Balancing Authority Code',
                                               'Ref_Electricity_Subregion_FuelCategory']]

**Comment by TJTapajyoti** [comment]
generation.py file

**Comment by WesIngwersen** [comment]
Yes, this is working.
