### ISSUE TITLE
egrid_facilities has multiple NERC for same Subregion

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#37]
This seems to be present in original eGRID data.
Proposed solution is to remove NERC from incoming StEWI and assign it via a lookup to a new correspondence table. 
Effect unknown but should be checked in generation.py, generation_mix.py, etc.

**Comment by WesIngwersen** [comment]
One place it had an effect was on the validation check. This [commit](https://github.com/USEPA/ElectricityLCI/commit/1106c3101db7104d9dc7968347203127352f9b2e) removed the duplicate NERC regions in the genmix data being used

**Comment by gschivley** [comment]
Can you clarify a little? Are you saying there are multiple NERC regions represented by facilities within a single eGRID subregion?

**Comment by WesIngwersen** [comment]
Resolved. Original egrid facility data have multiple NERCs for the same subregion but we correct this in egrid_facility
