### ISSUE TITLE
Use pandas read_excel parameters with EIA worksheets

### ISSUE THREAD

**Issue by gschivley** [USEPA/ElectricityLCI#39]
https://github.com/USEPA/ElectricityLCI/blob/a1f2346c1e3b644653711c385ece5b131b131929/electricitylci/eia923_generation.py#L21

Using the parameters `header=5` and `na_values='.'` removes the need to drop rows and convert fuel consumption/net generation to numeric.

**Comment by WesIngwersen** [comment]
Thanks for the update.
