### ISSUE TITLE
Wiki: Describe all parameters

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#48]
Need to be completed in
https://github.com/USEPA/ElectricityLCI/wiki/Description

**Comment by jump2conclusionsmatt** [comment]
Are these just the parameters available for model configuration files? I think the current implementation of commented reference yaml files satisfies this.

As for parameters in functions, I believe the added doc strings and wiki documentation for each module would address that.

**Comment by WesIngwersen** [comment]
I am good with the current documentation, closing
