### ISSUE TITLE
Build processes for Mexico for import to US

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#52]
We had existing code for this that worked for the template writer. This has not been updated to work for JSON-LD output. This would include flow name updates.  I have moved the old code for this to a [new branch](https://github.com/USEPA/ElectricityLCI/tree/Canada_mexico_process_builder)

**Comment by jump2conclusionsmatt** [comment]
This is partially complete - using ELCI_1, processes from Canada are created using a combination of Canada technology mixes (coal, gas, hydro, etc.) and applying those mixes against US-average profiles for those same technologies.
I'll rename the issue to reflect only Mexico.
