### ISSUE TITLE
Create main.py

### ISSUE THREAD

**Issue by gschivley** [USEPA/ElectricityLCI#56]
The current design puts all top-level functions in `__init__.py`. It isn't clear from the wiki how these should be accessed by a user. How about setting up a `main.py` (or something with a more specific name) that can be run as a script? 

```sh
python main.py
```

I'm also bringing this up because everything in the `__init__.py` is run whenever any functions are imported. Since commit 58cb1785be0230fd5132416dc315a331f6f14316 added the import of `model_name` to the top of __init__ it has become a little harder to build and test individual functions (need to comment the line out or set `set_model_name_with_stdin = False`).

**Comment by WesIngwersen** [comment]
Done by @gschivley
