### ISSUE TITLE
Create model config files representing all reasonable configurations

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#67]
As a first step, I'm starting a table of all input data and currently available years in electricitylci in [DataYears.md](https://github.com/USEPA/ElectricityLCI/blob/master/DataYears.md). I intend to add years for all other datasets. This table, along with an understanding of possible constraints of using different datasets together, is how I propose to determine possible config files. @jump2conclusionsmatt @TJTapajyoti

**Comment by WesIngwersen** [comment]
@TJTapajyoti @jump2conclusionsmatt Would somebody be willing to take this task over, or at least the part to populate DataYears.md, with the EIA, fuel mining and transport LCI, etc, to complete this table?

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt Please take a look at the DataYears,md and help me with some of the dates. CAN imports is missing. For EIA sources, I only included the years used in model 1 and 2. But the point of these is to determine the years at least from 2010 to present that the code would work for to grab that data

**Comment by jump2conclusionsmatt** [comment]
Just want to put my plan out there to see if it aligns with your expectations of reasonable.

- I plan on eliminating the various combinations of emissions data years (i.e., we wouldn't want 2014 eGRID, 2016 NEI, 2011 RCRA, 2015 TRI). It would be eGRID, NEI, TRI, CEMS 2016, RCRA 2015 or 2014/2013.
-  EIA files - I think we would want to be able to apply these inventories to different years of generation data (if replacing eGRID). So any combination above with any EIA data year. This would allow an assessment of the contributions of inventory vs. generation.
- Consumption mix to match EIA data, but this appears to be the most limiting dataset. Can do the 2014 mix using Hottle et al - and thus limit to eGRID or NERC regions? And then jump back to 2016+ for the IO consumption mix, limited to BA/FERC/US.
- T&D losses to align with EIA year.

**Comment by WesIngwersen** [comment]
@jump2conclusionsmatt . I intend the DataYears table only to be a record of all eachs for each source independently.  Then there is another step in actually deciding what feasible models are. So first, if you don't mind populating that table, then we can work on that next step.

**Comment by jump2conclusionsmatt** [comment]
I think I'm done making changes to DataYears.md. Started yesterday and finished today by making a test script to run through EIA data to see where things break, mostly due to column names changing.

**Comment by WesIngwersen** [comment]
I'm retracting my proposal to make all these model config files. I think its interesting for testing purposes but beyond the scope of what we currently have on our plate. That said I want us to continue to populate the DataYears table as data for new years become available. @jump2conclusionsmatt @TJTapajyoti
