### ISSUE TITLE
Include federal elementary flows list, impacts, and DQI in json-ld export

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/ElectricityLCI#68]
I think this could be done without too much difficulty. I think there'd essentially be an existing zip file in json-ld format containing all of the required info (likely can just use a json-ld exported by openLCA), copy that file into the output folder with a new name, and then the processes are inserted in - seems like the olca json-ld writer already supports this. This way, a user doesn't need to be responsible for generating their own databases to import the elci data.

**Comment by jump2conclusionsmatt** [comment]
Taken an initial shot at this - [branch](https://github.com/jump2conclusionsmatt/ElectricityLCI/tree/add_flows_to_jsonld). So far pretty simply - like 10 lines of code and a data file.
Unfortunately, it looks like there are handful of flows that aren't getting pulled in - resulting in NULL exchanges in processes. Suspect that I'm not passing all the relevant dataframes.

**Comment by WesIngwersen** [comment]
I don't think that we need to do this within this package.  We need to figure out better alternative works flows to get all the data together. We just need to document for now that use depends on import of these pieces into an olca db first, and where to get them.

**Comment by jump2conclusionsmatt** [comment]
Think this issue can be closed - the wiki directs users to the federal lca commons to download a core database. Easy enough for me.
