### ISSUE TITLE
Configuring to upstream coal and gas models

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#70]
To map and connect with the upstream coal and gas models, I am recommending adjustments to the categorization and flow names of the upstream processes and product flows, which I believe should only impact upstream_dict.py, and possible fuelname_1.csv. Because these processes span multiple stages (i.e. extraction and processing) I propose mapping them to the processing NAICs where the reference product flow will reside in the upstream models for both flows and processes.

e.g. "natural gas, at transmission" in 22: Utilities/2212: Natural Gas Distribution instead of 
21: Mining, Quarrying, and Oil and Gas Extraction/2111: Oil and Gas Extraction

 @jump2conclusionsmatt I can implement this change if all agree

**Comment by jump2conclusionsmatt** [comment]
I think this is fine.
