### ISSUE TITLE
Product flow categorization

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#71]
NAICS based categories for product flows need to be within the "Technosphere Flows" subfolder to match the FLCAC
![image](https://user-images.githubusercontent.com/44471635/69256533-99f9d900-0b87-11ea-8598-df49d22e3ca8.png)

**Comment by WesIngwersen** [comment]
This [commit](https://github.com/USEPA/ElectricityLCI/commit/a3d04a98f8681d0536705ab9b7763137f71924b6) should address it, but haven't tested it
