### ISSUE TITLE
Dictionary mismatches upon model creation

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/ElectricityLCI#77]
Linkages are not being created due to match failures. ELCI_1 model.

At generation mix stage (from main.py log):
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OIL - El Paso Electric Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for GAS - Electric Energy, Inc.
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLAR - Florida Municipal Power Pool
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLAR - Idaho Power Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLARTHERMAL - Nevada Power Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OTHF - Nevada Power Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OFSL - PJM Interconnection, LLC
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OTHF - PacifiCorp East
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for GEOTHERMAL - PacifiCorp West
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for BIOMASS - Portland General Electric Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OIL - Public Service Company of New Mexico
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLAR - South Carolina Electric & Gas Company
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for OFSL - Southwest Power Pool
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLAR - Southwestern Power Administration
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for WIND - Southwestern Power Administration
WARNING:generation_mix.py:olcaschema_genmix:Trouble matching dictionary for SOLAR - Western Area Power Administration - Desert

At consumption mix stage (from main.py log):
write consumption mix to dict
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Avista Corporation
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Bonneville Power Administration
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Public Utility District No. 1 of Chelan County
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - California Independent System Operator
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Duke Energy Progress West - Duke Energy Progress West
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Gridforce Energy Management, LLC
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce South - Gridforce South
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Idaho Power Company
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Los Angeles Department of Water and Power
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Nevada Power Company
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for New Smyrna Beach, Utilities Commission of - New Smyrna Beach, Utilities Commission of
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - PacifiCorp West
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Portland General Electric Company
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Puget Sound Energy, Inc.
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Seattle City Light
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Turlock Irrigation District
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - City of Tacoma, Department of Public Utilities, Light Division
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Western Area Power Administration - Upper Great Plains East - Western Area Power Administration - Upper Great Plains East
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - CAISO
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - Northwest
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Duke Energy Progress West - Southeast
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Duke Energy Progress West - US
WARNING:eia_io_trading.py:olca_schema_consumption_mix:Trouble matching dictionary for Gridforce Energy Management, LLC - US

See the attached images showing lack of providers in openLCA processes.

The results is a lack of providers in the JSON-LD export and therefore linkages not properly created in openLCA.

**Comment by WesIngwersen** [comment]
![MissingProvidersElectricityatgridconsumptionmixUS](https://user-images.githubusercontent.com/5831306/72180329-ece85380-33b4-11ea-9639-d6a4f282645e.PNG)
![MissingProvidersElectricityatgridgenerationmixElPaso](https://user-images.githubusercontent.com/5831306/72180403-1f924c00-33b5-11ea-89fa-793fa3091c24.PNG)

**Comment by WesIngwersen** [comment]
In the case of the requirement for OIL generation in El Paso, no generation process exists.

**Comment by WesIngwersen** [comment]
As for the consumption mix mismatches, there seems to be no generating regions for these. like 'Gridforce Energy Management', and some potential naming issues, like some duplicate name listing in the original data as in 'Western Area Power Administration - Upper Great Plains East - Western Area Power Administration - Upper Great Plains East'

**Comment by jump2conclusionsmatt** [comment]
Regarding the generation mixes, these are mostly due to a mismatch in the generation mix calculations vs. creating generation technologies. The generation mix calculation doesn't care whether the power plant burning the oil is an "oil power plant", it just sums up all the oil generation in a balancing authority area (for example). What is most likely happening in this and other cases is that there is no "oil" plant being generated because no power plants in El Paso use >95% oil.

**Comment by jump2conclusionsmatt** [comment]
Regarding the missing generators (e.g., El Paso - OIL), I think most of the cases will be similar to the El Paso case. In this case, the plant (FacilityID 50241) got categorized as a natural gas plant (in stewi). In 2016, this plant actually only burned DFO, so the percent generation from the primary fuel category was 0 and as a result, this plant got categorized as MIXED fuel plant and thus aggregated with the rest of the MIXED plants in the El Paso BA. This is what happens on the emission side of things.

When using EIA data for creating the generation mix, the algorithm chooses the primary fuel by choosing the fuel code that provided the most generation. In this case, it's DFO, so the generation mix for El Paso BA includes an input for an OIL generator.

I think these particular cases are pretty marginal. A possible workaround would be to ignore the stewi fuel classifications and calculate them on the fly using the eia923 data.

**Comment by jump2conclusionsmatt** [comment]
On consumption mixes.

Gridforce is interesting - it doesn't appear at all in EIA 860, which is the source of all plant BA data. The [project listing on their website](https://www.gridforce.com/projects/) shows that they have projects across the country. Surveying those plants in EIA860 data, these plants appear to be associated with the BA they're actually connected to? I'm not sure how we can reconcile this outside of hard-coding a fix for this handful of plants. The largest share of power provided by the Gridforce BA is around 2% for the Bonneville Power Administration. All others are less than a fraction of a percent.

The 3 plants associated with New Smyrna don't have any reported emissions or generation in EIA923.

Duke Energy Progress West is linked to a single solar PV project - there's a profile for it in the NETL solar PV data, so I'm not sure why that one's getting dropped. The only BA that uses Duke Energy Progress West is itself.

And lastly, there is also no Western Area Power Administration - Upper Great Plains East in EIA860.

**Comment by WesIngwersen** [comment]
> Regarding the missing generators (e.g., El Paso - OIL), I think most of the cases will be similar to the El Paso case. In this case, the plant (FacilityID 50241) got categorized as a natural gas plant (in stewi). In 2016, this plant actually only burned DFO, so the percent generation from the primary fuel category was 0 and as a result, this plant got categorized as MIXED fuel plant and thus aggregated with the rest of the MIXED plants in the El Paso BA. This is what happens on the emission side of things.
> 
> When using EIA data for creating the generation mix, the algorithm chooses the primary fuel by choosing the fuel code that provided the most generation. In this case, it's DFO, so the generation mix for El Paso BA includes an input for an OIL generator.
> 
> I think these particular cases are pretty marginal. A possible workaround would be to ignore the stewi fuel classifications and calculate them on the fly using the eia923 data.

@jump2conclusionsmatt  I'm surprised this issue is affecting ELCI_1 as reported in #116  because i didn't think the fuel types were eGRID fuel classifications were used .. i thought it was based on the EIA data.
this line in the config file
https://github.com/USEPA/ElectricityLCI/blob/0ffeac3300f435b1d32a110a0c209f505760c1bd/electricitylci/modelconfig/ELCI_1_config.yml#L22]
causes this if statement to be true
https://github.com/USEPA/ElectricityLCI/blob/0ffeac3300f435b1d32a110a0c209f505760c1bd/electricitylci/generation.py#L529
but i guess this only does a replacement when the existing fuel Category is NA

**Comment by jump2conclusionsmatt** [comment]
Agreed - maybe "replace_egrid" is a bit vague. I think explicity, we replaced eGRID CO2, SO2, and NOx emissions, and replaced eGrid-based generation mixes. I never really thought to replace the plant designations. Doing that probably takes care of the El Paso - oil.

I would like to try implementing a change to the FuelCategory based on EIA923 data and see how many of these go away. It also makes the replace_egrid option more true.

After that, as discussed, any missing technologies in generation mixes will be replaced with a US average profile for that technology (e.g., MISO-OFSL gets created using a notional US-OFSL).

**Comment by jump2conclusionsmatt** [comment]
Based on an initial run, changes in branch issues/77 fix the missing technology mixes. This was done by replacing all plant fuelcategory designations with those from EIA data - which is the same way the generation mix was being created. As of now, there are no warnings at generation_mix about not finding a matching dictionary. There's no need to substitute US profiles at this point. This may still pop up in the future if a generation mix includes a technology that has no emissions.

Issues #121, #124 still persist, along with the unmatched dictionaries when creating consumption mixes.

**Comment by WesIngwersen** [comment]
thanks @jump2conclusionsmatt. I'm wondering how much this is going to effect the data...could be potentially a large amount if the egrid fuel category is not based on the same data or similar approach. Any idea of how many plants end up changing fuel categories with this data change?

**Comment by jump2conclusionsmatt** [comment]
Duke Energy Progress West is also a separate issue. There is one solar plant (60880) that had 0 generation in 2016 - resulting in 0 emissions across the board. However because it has 0 generation, it's designated as a MIXED plant, and no generation mix is ever created because of 0 generation. I'm add this plant as a manual deletion. Just documenting here so that I have some place to reference in the yml file.

**Comment by jump2conclusionsmatt** [comment]
MIXED plant for Duke Energy Progress West is still being created for some reason. Changed the list of plants to keep to refer only to BAs with generation mixes in the dictionary.

Closing this issue.
