### ISSUE TITLE
Updates to flowlist causing null flow exchanges

### ISSUE THREAD

**Issue by bl-young** [USEPA/ElectricityLCI#81]
Due to some changes in FEDEFL, some mappings used in eLCI are now outdated, namely radioisotopes from upstream inventories (not StEWI based) including:

Radon-222
Thorium-230
Lead-210
Polonium-210
Radium-226
Cesium-137
Tritium
Radium-228
Radium-224
Iodine-131
Thorium-232
Strontium-90
Iodine-129

This resulted in exchanges with NULL values and display issues in openLCA. eLCI was generated specifying v.1.0.1 of FEDEFL. 
Updating the mapping file should fix this issue, but raises the question of whether mapping files need version control, if users are able to adjust the version of FEDEFL used.

**Comment by bl-young** [comment]
I believe this issue is now resolved based on #84 correct? @jump2conclusionsmatt

**Comment by jump2conclusionsmatt** [comment]
Agreed.
