### ISSUE TITLE
Missing data and configuration files when installing with pip

### ISSUE THREAD

**Issue by jump2conclusionsmatt** [USEPA/ElectricityLCI#99]
When running
`pip install git+https://github.com/USEPA/ElectricityLCI.git@setup_troubleshooting#egg=electricitylci`, the [model configuration folder](https://github.com/USEPA/ElectricityLCI/tree/setup_troubleshooting/electricitylci/modelconfig) and the [petroleum life cycle inventory data](https://github.com/USEPA/ElectricityLCI/tree/setup_troubleshooting/electricitylci/data/petroleum_inventory) folders do not get cloned.

**Comment by jump2conclusionsmatt** [comment]
Changes in [setup_troubleshooting](https://github.com/USEPA/ElectricityLCI/tree/setup_troubleshooting) appear to have fixed this. I change .gitignore and setup.py - I think the changes in setup.py are what did it.

**Comment by WesIngwersen** [comment]
Works for me
